### DISCUSSION TITLE
Snippet representation

### DISCUSSION THREAD

**Discussion by pokey** [cursorless-dev/cursorless#499] [Ideas]
We should come up with a good representation for our snippets.  Currently they look like the following:

```json
{
    "classDeclaration": {
        "definitions": [
            {
                "scope": {
                    "langIds": [
                        "python"
                    ]
                },
                "body": [
                    "class $name:",
                    "\t$body"
                ],
                "variables": {
                    "name": {
                        "formatter": "pascalCase"
                    }
                }
            },
            {
                "scope": {
                    "langIds": [
                        "typescript",
                        "typescriptreact",
                        "javascript",
                        "javascriptreact"
                    ]
                },
                "body": [
                    "class $name {",
                    "\t$body",
                    "}"
                ],
                "variables": {
                    "name": {
                        "formatter": "pascalCase"
                    }
                }
            }
        ],
        "description": "Class declaration",
        "variables": {
            "body": {
                "wrapperScopeType": "namedFunction"
            }
        },
        "insertionScopeType": "statement"
    }
}
```

This representation is hard to read

**Comment by pokey** [comment]
I was thinking something like the following, using [`toml`](https://toml.io/en/) preambles:

```toml
---
id = 'classDeclaration'
description = 'Class declaration'
insertionScopeType = 'statement'

[variables.name]

[variables.body]
wrapperScopeType = 'namedFunction'
---

---
id = 'classDeclaration'
langIds = ['python']

[variables.name]
formatter = 'pascalCase'
---
class {{ name }}:
    {{ body }}

---
id = 'classDeclaration'
langIds = ['typescript', 'typescriptreact', 'javascript', 'javascriptreact']

[variables.name]
formatter = 'pascalCase'
---
class {{ name }} {
    {{ body }}
}
```

Note how in the first "snippet", the body is empty, so we're just defining attributes without defining a snippet body, and we don't use `langIds`, which makes it global

Note also that we strip trailing newlines in the snippet body so that the user can add extra spacing for readability

Looks like there is a [`tree-sitter-toml`](https://github.com/ikatyang/tree-sitter-toml), as well as a cool pre-release [toml extension](https://marketplace.visualstudio.com/items?itemName=tamasfe.even-better-toml) that supports schemas, and the engine it uses is also available standalone as a JS package using wasm `yarn add @taplo/lib`

Looks like with that toml extension we can signal [important keys in the schema](https://taplo.tamasfe.dev/configuration/#schema-extension) via `initKeys` so that it will automatically add them in autocomplete

At its simplest, a snippet could just look like:

```toml
---
id = 'helloWorld'
---
Hello, {{ name }}!
```

**Reply by wenkokke** [reply]
What would the main advantage of using TOML will be?

**Comment by pokey** [comment]
[nunjucks](https://mozilla.github.io/nunjucks/templating.html) looks kinda nice as a templating language for the body of the snippet.

I like the way the [filters](https://mozilla.github.io/nunjucks/templating.html#filters) look; a lot like jq

Has a few VSCode extensions but [this one](https://marketplace.visualstudio.com/items?itemName=eseom.nunjucks-template) gets the best reviews it appears

**Reply by pokey** [reply]
We'd need to figure out how to handle the VSCode [special variables](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_variables) and [variable transforms](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_variable-transforms)

**Reply by pokey** [reply]
We also need to think about whether the looping syntax for iterating vector snippet holes (#445) is semantically rich enough for us to be able to keep track of them as they grow when used in #443

**Comment by pokey** [comment]
Fwiw [here](https://expressjs.com/en/resources/template-engines.html) is a list of template engines

**Comment by pokey** [comment]
Also fwiw here is how it would look if we used yaml for the metadata header:

```yaml
---
id: classDeclaration
description: Class declaration
insertionScopeType: statement
langIds:
- python
variables:
  body:
    wrapperScopeType: namedFunction
---

---
id: classDeclaration
langIds:
- python
variables:
  name:
    formatter: pascalCase
---
class {{ name }}:
    {{ body }}

---
id: classDeclaration
langIds:
- typescript
- typescriptreact
- javascript
- javascriptreact
variables:
  name:
    formatter: pascalCase
---
class {{ name }} {
    {{ body }}
}
```

if we go with yaml we'd want to register schema [like this](https://github.com/redhat-developer/vscode-yaml#mapping-a-schema-in-an-extension)

**Reply by wenkokke** [reply]
Wouldn’t it be easier to use multiline fields for the actual body, rather than separating YAML headers from non-YAML bodies? The only price to pay is that the body must be indented, but for that we gain that we do not have to write any parsers. Furthermore, it comes with a clear and unambiguous way to move onto the next snippet: dedenting.

**Reply by wenkokke** [reply]
Like so:

```yaml
---
id: classDeclaration
description: Class declaration
insertionScopeType: statement
langIds:
- python
variables:
  body:
    wrapperScopeType: namedFunction
...
---
id: classDeclaration
langIds:
- python
variables:
  name:
    formatter: pascalCase
body: |
  class {{ name }}:
      {{ body }}
...
---
id: classDeclaration
langIds:
- typescript
- typescriptreact
- javascript
- javascriptreact
variables:
  name:
    formatter: pascalCase
body: |
  class {{ name }} {
      {{ body }}
  }
...
```
