### ISSUE TITLE
Leverage same mechanism used by surrounding pairs in token whitespace removal logic

### ISSUE THREAD

**Issue by pokey** [cursorless-dev/cursorless#1590]
# The problem

As of https://github.com/cursorless-dev/cursorless/pull/1564, we determine whether we should remove whitespace in part based on whether the remaining adjacent token is an opening / closing pair.  This mostly works, but has a couple problems:

- We duplicate our source of truth about which tokens are considered opening / closing pairs
- The logic breaks down in complex cases, eg when it's not obvious whether a `"` is opening or closing (see test case below)

# The solution

We should find a way to leverage the code we use in surrounding pairs to determine if something is opening or closing

# Dependencies

- #1061 

# Test cases to add

The following test case fails today, but should pass:

```yaml
languageId: plaintext
command:
  version: 5
  spokenForm: chuck token
  action: {name: remove}
  targets:
    - type: primitive
      modifiers:
        - type: containingScope
          scopeType: {type: token}
  usePrePhraseSnapshot: true
initialState:
  documentContents: "\"aaa\".length + 1"
  selections:
    - anchor: {line: 0, character: 5}
      active: {line: 0, character: 12}
  marks: {}
finalState:
  documentContents: "\"aaa\" + 1"
  selections:
    - anchor: {line: 0, character: 5}
      active: {line: 0, character: 5}
```
