### ISSUE TITLE
confusing hat in fixture moveFirstWordZipBeforeFineTakeZip.yml

### ISSUE THREAD

**Issue by josharian** [cursorless-dev/cursorless#1767]
Consider `packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/scss/moveFirstWordZipBeforeFineTakeZip.yml`:

```yaml
languageId: scss
command:
  spokenForm: move first word zip before fine take zip
  version: 2
  targets:
    - type: primitive
      mark: {type: decoratedSymbol, symbolColor: default, character: z}
      modifiers:
        - type: ordinalRange
          scopeType: {type: word}
          anchor: 0
          active: 0
          excludeAnchor: false
          excludeActive: false
    - type: primitive
      mark: {type: decoratedSymbol, symbolColor: default, character: f}
      modifiers:
        - {type: position, position: before}
  usePrePhraseSnapshot: true
  action: {name: moveToTarget}
marksToCheck: [default.z]
initialState:
  documentContents: foo-bar baz-bongo
  selections:
    - anchor: {line: 0, character: 17}
      active: {line: 0, character: 17}
  marks:
    default.z:
      start: {line: 0, character: 8}
      end: {line: 0, character: 17}
    default.f:
      start: {line: 0, character: 0}
      end: {line: 0, character: 7}
finalState:
  documentContents: baz-foo-bar bongo
  selections:
    - anchor: {line: 0, character: 17}
      active: {line: 0, character: 17}
  marks:
    default.z:
      start: {line: 0, character: 12}
      end: {line: 0, character: 17}
    default.f:
      start: {line: 0, character: 0}
      end: {line: 0, character: 11}
```

In the finalState, the document is: `baz-foo-bar bongo`, and there's supposed to be a `z` hat in range 12-17, which is `bongo`. But there's no "z" in bongo.

Would it be OK to manually delete the `default.z` entry in `finalState` there? Or is it testing something non-obvious?
