### ISSUE TITLE
Fix `that` mark when targets get merged

### ISSUE THREAD

**Issue by pokey** [cursorless-dev/cursorless#780]
Once (FIXME: PR) is merged, during our target merging, we will consider two targets equivalent if they have the same `that` mark, constructing a new target which arbitrarily picks one of their `that` marks. We would prefer to create a list-valued `that` mark instead when we merge them.

The following test should pass:

```yaml
languageId: plaintext
command:
  spokenForm: drink this
  version: 2
  targets:
    - type: primitive
      mark: { type: cursor }
  usePrePhraseSnapshot: true
  action: { name: editNewLineBefore }
initialState:
  documentContents: hello world
  selections:
    - anchor: { line: 0, character: 2 }
      active: { line: 0, character: 2 }
    - anchor: { line: 0, character: 4 }
      active: { line: 0, character: 4 }
    - anchor: { line: 0, character: 8 }
      active: { line: 0, character: 8 }
  marks: {}
finalState:
  documentContents: |-

    hello world
  selections:
    - anchor: { line: 0, character: 0 }
      active: { line: 0, character: 0 }
  thatMark:
    - anchor: { line: 1, character: 2 }
      active: { line: 1, character: 2 }
    - anchor: { line: 0, character: 4 }
      active: { line: 0, character: 4 }
    - anchor: { line: 0, character: 8 }
      active: { line: 0, character: 8 }
fullTargets: [{ type: primitive, mark: { type: cursor }, modifiers: [] }]
```

Today, the `that` mark will only include the first selection.
